### ISSUE TITLE
[Bug] Georeferencing session does not save properly after extending

### ISSUE THREAD

**Issue by hdevine825** [mradamcox/ohmg#134] opened 2023-05-30 12:48 UTC
**Describe the problem**
After clicking "I need more time" on the session expiration notice during georeferencing the session does not save properly.

**To Reproduce**
1. Open a georeferencing session
2. Wait for the session expiration notice to appear and select "I need more time"
3. Save the session
4. After being directed back to the map page it initially shows the georeferencing session as completed in session history, but after refreshing it disappears and shows "Status: georeferencing in progress..."

![image](https://github.com/mradamcox/ohmg/assets/12535864/bd436a13-d0f2-414b-bfb4-4e24be92f987)

**Environment info:**
 - Device: Laptop
 - Operating System: Ubuntu
 - Browser: Firefox

**Additional context**
See this example page where I encountered the issue: https://oldinsurancemaps.net/resource/6013

**Comment by mradamcox** [comment] 2023-05-30 14:20
@hdevine825 Thanks for reporting this. I'll have a look at it as soon as I can. Seems like the time extension doesn't get registered and the sessions gets lost because of it. Definitely a regression.

**Comment by mradamcox** [comment] 2023-06-02 16:47
@hdevine825 Fix for this is now deployed.

**Closed by mradamcox** 2023-06-02 16:47 UTC
Labels: bug
